Controllers/AdminController.cs
using CrudMVC_App.DAL;
using CrudMVC_App.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CrudMVC_App.Controllers
{
    [Authorize(Roles = Roles.Admin)]
    public class AdminController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context; 

        public AdminController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: Admin/Users
        public IActionResult Users(int page = 1)
        {
            int pageSize = 5;

            var users = _userManager.Users
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            ViewBag.CurrentPage = page;

            return View(users);
        }

        // GET: Admin/DeleteUser/id
        public async Task<IActionResult> DeleteUser(string id)
        {
            if (id == null) return NotFound();

            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();

            return View(user);
        }

        // POST: Admin/DeleteUser/id
        [HttpPost, ActionName("DeleteUser")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUserConfirmed(string id)
        {
            var currentUserId = _userManager.GetUserId(User);

            // ❌ Prevent self delete
            if (id == currentUserId)
            {
                TempData["Error"] = "You cannot delete your own account.";
                return RedirectToAction(nameof(Users));
            }

            var user = await _userManager.FindByIdAsync(id);

            if (user != null)
            {
                
                user.IsDeleted = true;
                user.DeletedOn = DateTime.Now;
                await _userManager.UpdateAsync(user);
                //await _userManager.DeleteAsync(user);

                _context.AuditLogs.Add(new AuditLog
                {
                    Action = "Delete User",
                    PerformedBy = User.Identity.Name,
                    TargetUser = user.Email,
                    Timestamp = DateTime.Now
                });

                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Users));
        }


        public async Task<IActionResult> EditUserRoles(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var roles = await _userManager.GetRolesAsync(user);

            ViewBag.AllRoles = new[] { Roles.Admin, Roles.User };

            return View((user, roles));
        }

        [HttpPost]
        public async Task<IActionResult> EditUserRoles(string userId, string[] roles)
        {
            var user = await _userManager.FindByIdAsync(userId);

            var existingRoles = await _userManager.GetRolesAsync(user);

            await _userManager.RemoveFromRolesAsync(user, existingRoles);
            await _userManager.AddToRolesAsync(user, roles);

            return RedirectToAction(nameof(Users));
        }

        
        public async Task<IActionResult> RestoreUser(string id)
        {
            var user = await _userManager.Users
                .IgnoreQueryFilters()
                .FirstOrDefaultAsync(u => u.Id == id);

            if (user == null) return NotFound();

            user.IsDeleted = false;
            user.DeletedOn = null;
            _context.AuditLogs.Add(new AuditLog
            {
                Action = "Restore User",
                PerformedBy = User.Identity.Name,
                TargetUser = user.Email,
                Timestamp = DateTime.Now
            });

            await _context.SaveChangesAsync();
            await _userManager.UpdateAsync(user);

            return RedirectToAction(nameof(Users));
        }

        public IActionResult AuditLogs()
        {
            return View(_context.AuditLogs
                .OrderByDescending(a => a.Timestamp)
                .ToList());
        }

        public async Task<IActionResult> Enable2FA(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();

            await _userManager.SetTwoFactorEnabledAsync(user, true);

            return RedirectToAction(nameof(Users));
        }

    }
}

Controllers/ProductsController.cs
using CrudMVC_App.BLL.Services;
using CrudMVC_App.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CrudMVC_App.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        //private readonly IProductService _service;
        private readonly IUnitOfWork _uow;

        public ProductsController(IUnitOfWork uow)
        {
           // _service = service;
            _uow = uow;
        }
        
        //[Authorize(Roles = Roles.User)]
        public IActionResult Index()
        {
            return View(_uow.Products.GetAll());
        }
        [Authorize(Roles = Roles.Admin)]
        public IActionResult Create() => View();

        [HttpPost]
        [Authorize(Roles = Roles.Admin)]
        public IActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                //_service.Create(product);
                _uow.Products.Add(product);
                _uow.Save();
                return RedirectToAction("Index");
            }
            return View(product);
        }
        [Authorize(Roles = Roles.Admin)]
        public IActionResult Edit(int id)
        {
            return View(_uow.Products.GetById(id));
        }

        [HttpPost]
        [Authorize(Roles = Roles.Admin)]
        public IActionResult Edit(Product product)
        {
            //_service.Edit(product);
            _uow.Products.Update(product);
            return RedirectToAction("Index");
        }
        [Authorize(Roles = Roles.Admin)]
        public IActionResult Delete(int id)
        {
            // _service.Remove(id);
            _uow.Products.Delete(id);
            _uow.Save();
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
@using CrudMVC_App.Entities
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudMVC_App</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudMVC_App.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrudMVC_App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @* <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul> *@

                    <!-- Left Menu -->
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(Roles.Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link"
                                   asp-controller="Admin"
                                   asp-action="Users">
                                    Manage Users
                                </a>
                            </li>
                        }
                        @if (User.IsInRole(Roles.Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link"
                                   asp-controller="Admin"
                                   asp-action="AuditLogs">
                                    Audit Logs
                                </a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark"
                                   asp-controller="Products"
                                   asp-action="Index">
                                    Products
                                </a>
                            </li>
                        }
                    </ul>

                    <!-- Right Menu (Auth) -->
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <span class="nav-link text-dark">
                                    Hello, @User.Identity.Name
                                </span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-danger"
                                   asp-controller="Account"
                                   asp-action="Logout">
                                    Logout
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark"
                                   asp-controller="Account"
                                   asp-action="Login">
                                    Login
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark"
                                   asp-controller="Account"
                                   asp-action="Register">
                                    Register
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CrudMVC_App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- DataTables -->
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>